<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />

    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->

    <style type="text/css">
         /* Yubico Mice header*/
        .yubi-key-input {
            background: white url("<?php echo $this->getSkinUrl('images/n98_yubikey/yubiright_16x16.gif') ?>") no-repeat 2px 2px !important;
            padding-left: 20px !important;
        }
    </style>

</head>
<body id="page-login" onload="document.forms.loginForm.otp.focus();">
<div class="login-container">
    <div class="login-box">
        <form method="post" action="" id="loginForm">
            <div class="login-form">
                <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                <h2><?php echo Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                <div id="messages">
                    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                </div>
                <div class="input-box"><label for="login"><?php echo Mage::helper('n98_yubikey')->__('YubiKey / One time password:') ?></label><br />
                    <input type="password" id="login" name="otp" class="yubi-key-input required-entry input-text" value="" />
                </div>
                <div class="input-box input-right">
                    <ul>
                        <li><?php echo Mage::helper('n98_yubikey')->__('1. Place your YubiKey in the USB-port.') ?></li>
                        <li><?php echo Mage::helper('n98_yubikey')->__('2. Touch YubiKey button.') ?></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
        </form>

        <div class="bottom"></div>
        <script type="text/javascript">
            var loginForm = new varienForm('loginForm');
        </script>
    </div>
</div>
</body>
</html>